{% set name = "chainladder" %}
{% set version = "0.7.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chainladder-{{ version }}.tar.gz
  sha256: f41b2371d520e3eee13ae493ae563639ab2461524c47741f18ccc8996cdf772d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.5
  run:
    - joblib
    - numpy >=1.12.0
    - pandas >=0.23.0
    - python >=3.5
    - scikit-learn >=0.18.0
    - scipy
    - sparse
    - xlcompose >=0.2.4
    - dill

test:
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  license: MPL-2.0
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
