{% set name = "chainladder" %}
{% set version = "0.8.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chainladder-{{ version }}.tar.gz
  sha256: 4c33950e11b03d29e756e158bc57e69dc647eda11c98437696e2c1337e830f62

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.5
  run:
    - joblib
    - numpy >=1.12.0
    - pandas >=0.23.0
    - python >=3.5
    - scikit-learn >=0.23.0
    - scipy
    - matplotlib
    - numba
    - sparse
    - dill
    - patsy

test:
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  license: MPL-2.0
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
