{% set name = "chainladder" %}
{% set version = "0.8.25" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chainladder-{{ version }}.tar.gz
  sha256: 0ffcee964df3d1bc126be508fe623d39b51c8a15e48c4a0535116c0f6142e146

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.5
  run:
    - joblib
    - numpy >=1.12.0
    - pandas >=0.23.0
    - python >=3.5
    - scikit-learn >=0.23.0
    - scipy
    - matplotlib
    - numba
    - sparse
    - dill
    - patsy

test:
  imports:
    - chainladder
    - chainladder.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/casact/chainladder-python
  summary: Chainladder Package - P&C Loss Reserving package
  license: MPL-2.0
  # License file manually packaged. See https://github.com/casact/chainladder-python/pull/102
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbogaardt
